### ISSUE TITLE
Error when trying to run train.py

### ISSUE THREAD

**Issue by wisan-dhammatorn** [onpix/LCDPNet#5]
I got error messages when I tried to run train.py and test.py. How can I solve the problems?
Thank you in advance.
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

Missing logger folder: /home/arm/Desktop/LCDPNet/tb_logs/lcdpnet:ours@ours
train_ds - GT Directory path: [yellow]['raise/gt/*.png'][/yellow]
train_ds - Input Directory path: [yellow]['raise/input/*.png'][/yellow]
train_ds Dataset length: 607, batch num: 37
valid_ds - GT Directory path: [yellow]['raise/valid-gt/*.png'][/yellow]
valid_ds - Input Directory path: [yellow]['raise/valid-input/*.png'][/yellow]
valid_ds Dataset length: 0, batch num: 0
Error occured! Your ds is: TYPE=valid_ds, config:
{'class': 'img_dataset', 'name': 'ours-cslab.valid', 'input': ['raise/valid-input/*.png'], 'GT': ['raise/valid-gt/*.png']}
Error executing job with overrides: ['name=ours', 'num_epoch=200', 'log_every=2000', 'valid_every=20']
Traceback (most recent call last):
  File "src/train.py", line 124, in main
    trainer.fit(model, datamodule, ckpt_path=opt.checkpoint_path)
  File "/home/arm/anaconda3/envs/cloned_py37/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 604, in fit
    self, self._fit_impl, model, train_dataloaders, val_dataloaders, datamodule, ckpt_path
  File "/home/arm/anaconda3/envs/cloned_py37/lib/python3.7/site-packages/pytorch_lightning/trainer/call.py", line 36, in _call_and_handle_interrupt
    return trainer.strategy.launcher.launch(trainer_fn, *args, trainer=trainer, **kwargs)
  File "/home/arm/anaconda3/envs/cloned_py37/lib/python3.7/site-packages/pytorch_lightning/strategies/launchers/subprocess_script.py", line 90, in launch
    return function(*args, **kwargs)
  File "/home/arm/anaconda3/envs/cloned_py37/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 645, in _fit_impl
    self._run(model, ckpt_path=self.ckpt_path)
  File "/home/arm/anaconda3/envs/cloned_py37/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 1037, in _run
    self._call_setup_hook()  # allow user to setup lightning_module in accelerator environment
  File "/home/arm/anaconda3/envs/cloned_py37/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 1284, in _call_setup_hook
    self._call_lightning_datamodule_hook("setup", stage=fn)
  File "/home/arm/anaconda3/envs/cloned_py37/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 1361, in _call_lightning_datamodule_hook
    return fn(*args, **kwargs)
  File "/home/arm/Desktop/LCDPNet/src/data/img_dataset.py", line 185, in setup
    self.valid_dataset = ImagesDataset(opt, ds_type=VALID_DATA, transform=self.valid_transform, batchsize=opt.valid_batchsize)
  File "/home/arm/Desktop/LCDPNet/src/data/img_dataset.py", line 99, in __init__
    raise RuntimeError(f'[ Err ] Dataset input nums is 0!')
RuntimeError: [ Err ] Dataset input nums is 0!

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.

**Comment by onpix** [comment]
This is because your validation dataset has no images. There may be some problems with your validation dataset path config.
